theme: jekyll-theme-minimal
title: Asset library site for MPPC23 Workshop: Empowering Robotic Process Automation Enthusiasts: Harnessing the Potential of Power Automate
description: Workshop: Empowering Robotic Process Automation Enthusiasts: Harnessing the Potential of Power Automate
